version: 2
jobs:
  py36:
    working_directory: ~/spoffy
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-deps-{{ checksum "poetry.lock" }}
      - run:
          name: install poetry
          command: |
            curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
            echo 'export PATH="$HOME/.poetry/bin:$PATH"' >> $BASH_ENV
      - run:
          name: install dependencies
          command: poetry install
      - save_cache:
          key: v1-pip-deps-{{ checksum "poetry.lock" }}
          paths:
            - ~/.local
            - ~/.cache
      - run:
          name: lint
          command: poetry run flake8 spoffy
      - run:
          name: type-check
          command: poetry run mypy spoffy
      - run:
          name: test
          command: poetry run pytest tests
  py37:
    working_directory: ~/spoffy
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-deps-{{ checksum "poetry.lock" }}
      - run:
          name: install poetry
          command: |
            curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
            echo 'export PATH="$HOME/.poetry/bin:$PATH"' >> $BASH_ENV
      - run:
          name: install dependencies
          command: poetry install
      - save_cache:
          key: v1-pip-deps-{{ checksum "poetry.lock" }}
          paths:
            - ~/.local
            - ~/.cache
      - run:
          name: lint
          command: poetry run flake8 spoffy
      - run:
          name: type-check
          command: poetry run mypy spoffy
      - run:
          name: test
          command: poetry run pytest tests

workflows:
  version: 2
  test-all:
    jobs:
      - py36
      - py37
