name: Python package

# Run on push to the master branch and any pull request
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Poetry dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pypoetry
          !~/.cache/pypoetry/artifacts
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.6.1

    - name: Install dependencies
      run: poetry install

    - name: Lint with flake8
      run: poetry run flake8 spoffy

    - name: Type-check
      run: poetry run mypy spoffy

    - name: Test with pytest
      run: poetry run pytest tests
